language: cpp
sudo: required

install:

 - if [ "$CXX" = "g++" ]; then add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - if [ "$CXX" = "g++" ]; then add-apt-repository -y ppa:zoogie/sdl2-snapshots; fi
 - if [ "$CXX" = "g++" ]; then apt-get update; fi
 - if [ "$CXX" = "g++" ]; then apt-get install libsdl2-dev; fi
 - if [ "$CXX" = "g++" ]; then apt-get install -y gcc-4.8; fi
 - if [ "$CXX" = "g++" ]; then apt-get install -y g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
 - if [ "$CXX" = "g++" ]; then update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi

script:
    - if [ "$CXX" = "g++" ]; then g++ --version; fi
    - if [ "$CXX" = "g++" ]; then clang++ --version; fi
    - make clean
    - make
    - ./algorithm
compiler:
- clang++
- g++
os:
- linux
- osx
branches:
 only:
 - master
notifacations:
 email: false
 irc:
 - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
 global:
 - LANG="en_US.UTF-8"
