language: cpp
sudo: required
services:
        - docker
before_install:
        - docker build -t ximena-gcc-app .
        - docker images
script:
        - docker run ximena-gcc-app
branches:
 only:
 - master
notifacations:
 email: false
 irc:
 - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
 global:
 - LANG="en_US.UTF-8"

 - CODECLIMATE_REPO_TOKEN="46146344402d8fa58a23988a29ba69d9e2e96b738ac6e74a61519f063207a03c"
