language: cpp
sudo: required

install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
 - sudo apt-get update
 - sudo apt-get install libsdl2-dev
 - sudo apt-get install -y gcc-4.8
 - sudo apt-get install -y g++-4.8
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

script:
    - make clean
    - make
    - ./algorithm
compiler:
- clang
- g++
os:
- linux
- osx
branches:
 only:
 - master
notifacations:
 email: false
 irc:
 - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
 global:
 - LANG="en_US.UTF-8"
